services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: abdofahmi
            MONGO_INITDB_ROOT_PASSWORD: password
        networks:
            - app-network
        volumes:
            - mongo-data:/data
    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: always
        depends_on:
            - mongodb
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: abdofahmi
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
        networks:
            - app-network
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        container_name: Recipe_Bank
        depends_on:
            - mongodb
        ports:
            - 8080:8080
        environment:
            SPRING_DATA_MONGODB_URI: mongodb://abdofahmi:password@mongodb:27017/recipes_db?authSource=admin
        networks:
            - app-network

volumes:
    mongo-data: {}

networks:
    app-network:
        driver: bridge


