services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=abdofahmi
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo-data:/data
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        depends_on:
            - mongodb
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=abdofahmi
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_PORT=27017
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017

volumes:
    mongo-data: {}


