services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${spring_data_mongo_username}
            MONGO_INITDB_ROOT_PASSWORD: ${spring_data_mongo_password}
        networks:
            - app-network
        volumes:
            - mongo-data:/data
    mongo-express:
        image: mongo-express:latest
        container_name: mongo-express
        restart: always
        depends_on:
            - mongodb
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${spring_data_mongo_username}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${spring_data_mongo_password}
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
        networks:
            - app-network
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        container_name: Recipe_Bank
        depends_on:
            - mongodb
        ports:
            - 8080:8080
        environment:
            SPRING_DATA_MONGODB_URI: ${spring_data_mongo_uri}
        networks:
            - app-network

volumes:
    mongo-data: {}

networks:
    app-network:
        driver: bridge


